version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - mynetwork
    volumes:
      - .:/app

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork
    ports:
      - "5434:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mydomain.com"
      PGADMIN_DEFAULT_PASSWORD: "adminpassword"
      PGADMIN_DEFAULT_SERVER: postgres
    networks:
      - mynetwork
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  mynetwork: